### Hae kaikki myyntitapahtumat
GET http://localhost:8080/api/myyntitapahtumat
Authorization: Basic user user


### Hae myyntitapahtuma ID:llä
GET http://localhost:8080/api/myyntitapahtumat/1
Authorization: Basic admin admin


### Hae myyntitapahtuma ID:llä, jota ei ole
GET http://localhost:8080/api/myyntitapahtumat/99999
Authorization: Basic user user